# Generated by Django 4.1.2 on 2022-11-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0003_answer_modify_date_question_modify_date_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
