# Generated by Django 4.1.2 on 2022-11-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0004_alter_comment_modify_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="Questionanswer", new_name="question",
        ),
    ]
